import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';
import { Extraction, ActionPlan } from '@/types';

Font.register({ family: 'NotoSansDevanagari', src: '/fonts/NotoSansDevanagari-Regular.ttf' });
Font.register({ family: 'NotoSansTamil', src: '/fonts/NotoSansTamil-Regular.ttf' });

// Localized UI labels for PDF sections — values are translated by backend, headings by this map
const LABELS: Record<string, Record<string, string>> = {
  English: {
    reportTitle: 'Legal Document Report',
    docIdLabel: 'Document ID', exportedLabel: 'Exported', languageLabel: 'Language',
    caseDetails: 'Case Details', caseNumber: 'Case Number', court: 'Court', judge: 'Judge',
    caseType: 'Case Type', filingDate: 'Filing Date', hearingDate: 'Hearing Date',
    parties: 'Parties', plaintiff: 'Plaintiff', defendant: 'Defendant', otherParty: 'Other Party',
    finalOrder: 'Final Order', deadlines: 'Deadlines', citations: 'Citations', pageAbbrev: 'p.',
    actionPlan: 'Action Plan', decision: 'Decision', department: 'Department',
    requiredActions: 'Required Actions', dueLabel: 'Due',
    footerText: 'Generated by Jurix AI · jurix-ai-client.vercel.app',
  },
  Hindi: {
    reportTitle: 'कानूनी दस्तावेज़ रिपोर्ट',
    docIdLabel: 'दस्तावेज़ ID', exportedLabel: 'निर्यात तिथि', languageLabel: 'भाषा',
    caseDetails: 'मामले का विवरण', caseNumber: 'मामला संख्या', court: 'न्यायालय', judge: 'न्यायाधीश',
    caseType: 'मामले का प्रकार', filingDate: 'दायर तिथि', hearingDate: 'सुनवाई तिथि',
    parties: 'पक्षकार', plaintiff: 'वादी', defendant: 'प्रतिवादी', otherParty: 'अन्य पक्ष',
    finalOrder: 'अंतिम आदेश', deadlines: 'समय-सीमाएं', citations: 'उद्धरण', pageAbbrev: 'पृ.',
    actionPlan: 'कार्य योजना', decision: 'निर्णय', department: 'विभाग',
    requiredActions: 'आवश्यक कार्रवाइयां', dueLabel: 'नियत तिथि',
    footerText: 'Jurix AI द्वारा निर्मित · jurix-ai-client.vercel.app',
  },
  Marathi: {
    reportTitle: 'कायदेशीर दस्तावेज अहवाल',
    docIdLabel: 'दस्तावेज ID', exportedLabel: 'निर्यात तारीख', languageLabel: 'भाषा',
    caseDetails: 'प्रकरण तपशील', caseNumber: 'प्रकरण क्रमांक', court: 'न्यायालय', judge: 'न्यायाधीश',
    caseType: 'प्रकरणाचा प्रकार', filingDate: 'दाखल तारीख', hearingDate: 'सुनावणी तारीख',
    parties: 'पक्षकार', plaintiff: 'फिर्यादी', defendant: 'प्रतिवादी', otherParty: 'इतर पक्ष',
    finalOrder: 'अंतिम आदेश', deadlines: 'मुदती', citations: 'संदर्भ', pageAbbrev: 'पृ.',
    actionPlan: 'कृती योजना', decision: 'निर्णय', department: 'विभाग',
    requiredActions: 'आवश्यक कृती', dueLabel: 'मुदत',
    footerText: 'Jurix AI द्वारे तयार · jurix-ai-client.vercel.app',
  },
  Tamil: {
    reportTitle: 'சட்ட ஆவண அறிக்கை',
    docIdLabel: 'ஆவண ID', exportedLabel: 'ஏற்றுமதி தேதி', languageLabel: 'மொழி',
    caseDetails: 'வழக்கு விவரங்கள்', caseNumber: 'வழக்கு எண்', court: 'நீதிமன்றம்', judge: 'நீதிபதி',
    caseType: 'வழக்கு வகை', filingDate: 'தாக்கல் தேதி', hearingDate: 'விசாரணை தேதி',
    parties: 'தரப்பினர்', plaintiff: 'வாதி', defendant: 'பிரதிவாதி', otherParty: 'மற்ற தரப்பு',
    finalOrder: 'இறுதி உத்தரவு', deadlines: 'காலக்கெடுக்கள்', citations: 'மேற்கோள்கள்', pageAbbrev: 'பக்.',
    actionPlan: 'செயல் திட்டம்', decision: 'முடிவு', department: 'துறை',
    requiredActions: 'தேவையான நடவடிக்கைகள்', dueLabel: 'நியமிக்கப்பட்ட தேதி',
    footerText: 'Jurix AI மூலம் உருவாக்கப்பட்டது · jurix-ai-client.vercel.app',
  },
  French: {
    reportTitle: 'Rapport de document juridique',
    docIdLabel: 'ID du document', exportedLabel: "Date d'export", languageLabel: 'Langue',
    caseDetails: "Détails de l'affaire", caseNumber: 'Numéro de dossier', court: 'Tribunal', judge: 'Juge',
    caseType: "Type d'affaire", filingDate: 'Date de dépôt', hearingDate: "Date d'audience",
    parties: 'Parties', plaintiff: 'Demandeur', defendant: 'Défendeur', otherParty: 'Autre partie',
    finalOrder: 'Ordonnance finale', deadlines: 'Délais', citations: 'Citations', pageAbbrev: 'p.',
    actionPlan: "Plan d'action", decision: 'Décision', department: 'Département',
    requiredActions: 'Actions requises', dueLabel: 'Échéance',
    footerText: 'Généré par Jurix AI · jurix-ai-client.vercel.app',
  },
  Spanish: {
    reportTitle: 'Informe de documento legal',
    docIdLabel: 'ID del documento', exportedLabel: 'Fecha de exportación', languageLabel: 'Idioma',
    caseDetails: 'Detalles del caso', caseNumber: 'Número de caso', court: 'Tribunal', judge: 'Juez',
    caseType: 'Tipo de caso', filingDate: 'Fecha de presentación', hearingDate: 'Fecha de audiencia',
    parties: 'Partes', plaintiff: 'Demandante', defendant: 'Demandado', otherParty: 'Otra parte',
    finalOrder: 'Orden final', deadlines: 'Plazos', citations: 'Citas', pageAbbrev: 'p.',
    actionPlan: 'Plan de acción', decision: 'Decisión', department: 'Departamento',
    requiredActions: 'Acciones requeridas', dueLabel: 'Vencimiento',
    footerText: 'Generado por Jurix AI · jurix-ai-client.vercel.app',
  },
};

function fontFamily(language: string): string {
  if (language === 'Hindi' || language === 'Marathi') return 'NotoSansDevanagari';
  if (language === 'Tamil') return 'NotoSansTamil';
  return 'Helvetica';
}

const s = StyleSheet.create({
  page: { padding: 52, fontSize: 10, color: '#111827', backgroundColor: '#ffffff', lineHeight: 1.4 },

  // Header
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 28, paddingBottom: 18, borderBottomWidth: 1, borderBottomColor: '#e5e7eb' },
  brand: { fontSize: 18, fontWeight: 'bold', color: '#111827' },
  brandSub: { fontSize: 8, color: '#9ca3af', marginTop: 3, letterSpacing: 0.5 },
  metaRight: { alignItems: 'flex-end' },
  metaLabel: { fontSize: 7.5, color: '#9ca3af', letterSpacing: 0.3 },
  metaValue: { fontSize: 8.5, color: '#374151', marginTop: 1.5 },

  // Sections
  section: { marginBottom: 22 },
  sectionTitle: { fontSize: 7.5, color: '#9ca3af', letterSpacing: 2, textTransform: 'uppercase', marginBottom: 8, fontWeight: 'bold' },

  // Key-value card
  card: { backgroundColor: '#f9fafb', borderRadius: 5, padding: 14, borderWidth: 1, borderColor: '#e5e7eb' },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8, gap: 8 },
  rowLast: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 },
  label: { color: '#6b7280', width: 110, flexShrink: 0, fontSize: 9.5 },
  value: { flex: 1, textAlign: 'right', color: '#111827', fontSize: 9.5 },

  // Body text (final order)
  bodyText: { lineHeight: 1.75, color: '#374151', fontSize: 9.5 },

  // Bullet lists (deadlines)
  listRow: { flexDirection: 'row', marginBottom: 6, alignItems: 'flex-start' },
  bullet: { color: '#f59e0b', marginRight: 8, fontSize: 14, lineHeight: 1 },
  listText: { flex: 1, color: '#374151', lineHeight: 1.5, fontSize: 9.5 },

  // Citations
  citRow: { flexDirection: 'row', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#f3f4f6', gap: 10 },
  citPage: { color: '#9ca3af', width: 28, flexShrink: 0, fontSize: 9, fontFamily: 'Courier' },
  citText: { flex: 1, color: '#374151', lineHeight: 1.5, fontSize: 9.5 },

  // Decision badge
  badge: { fontSize: 9, fontWeight: 'bold', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 3 },
  badgeComply: { backgroundColor: '#dcfce7', color: '#166534' },
  badgeAppeal: { backgroundColor: '#e0e7ff', color: '#3730a3' },

  // Action plan rows
  actionRow: { flexDirection: 'row', paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: '#f3f4f6', gap: 10 },
  actionNum: { color: '#9ca3af', width: 22, flexShrink: 0, fontSize: 9, fontFamily: 'Courier', paddingTop: 1 },
  actionBody: { flex: 1 },
  actionText: { color: '#374151', lineHeight: 1.55, fontSize: 9.5 },
  actionDeadline: { color: '#9ca3af', marginTop: 3, fontSize: 8.5 },

  // Footer
  footer: { position: 'absolute', bottom: 30, left: 52, right: 52, flexDirection: 'row', justifyContent: 'space-between', fontSize: 7.5, color: '#9ca3af', borderTopWidth: 1, borderTopColor: '#e5e7eb', paddingTop: 8 },
});

interface Props {
  documentId: string;
  extraction?: Extraction;
  actionPlan?: ActionPlan;
  language: string;
  exportDate: string;
}

export function LegalDocumentPDF({ documentId, extraction, actionPlan, language, exportDate }: Props) {
  const ff = fontFamily(language);
  const L = LABELS[language] ?? LABELS.English;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const txt = (text: string | undefined | null, style?: any) => (
    <Text style={[{ fontFamily: ff }, style]}>{text || 'N/A'}</Text>
  );

  return (
    <Document>
      <Page size="A4" style={[s.page, { fontFamily: ff }]}>

        {/* ── Header ── */}
        <View style={s.headerRow}>
          <View>
            <Text style={[s.brand, { fontFamily: 'Helvetica-Bold' }]}>Jurix AI</Text>
            <Text style={s.brandSub}>{L.reportTitle}</Text>
          </View>
          <View style={s.metaRight}>
            <Text style={s.metaLabel}>{L.docIdLabel}</Text>
            <Text style={[s.metaValue, { fontFamily: 'Courier' }]}>{documentId.slice(0, 20)}…</Text>
            <Text style={[s.metaLabel, { marginTop: 5 }]}>{L.exportedLabel}</Text>
            <Text style={s.metaValue}>{exportDate}</Text>
            {language !== 'English' && (
              <>
                <Text style={[s.metaLabel, { marginTop: 5 }]}>{L.languageLabel}</Text>
                <Text style={s.metaValue}>{language}</Text>
              </>
            )}
          </View>
        </View>

        {/* ── Case Details ── */}
        <View style={s.section} wrap={false}>
          <Text style={s.sectionTitle}>{L.caseDetails}</Text>
          <View style={s.card}>
            <View style={s.row}><Text style={s.label}>{L.caseNumber}</Text>{txt(extraction?.case_details?.case_number, s.value)}</View>
            <View style={s.row}><Text style={s.label}>{L.court}</Text>{txt(extraction?.case_details?.court, s.value)}</View>
            <View style={s.row}><Text style={s.label}>{L.judge}</Text>{txt(extraction?.case_details?.judge, s.value)}</View>
            <View style={s.row}><Text style={s.label}>{L.caseType}</Text>{txt(extraction?.case_details?.case_type, s.value)}</View>
            <View style={s.row}><Text style={s.label}>{L.filingDate}</Text>{txt(extraction?.case_details?.filing_date, s.value)}</View>
            <View style={s.rowLast}><Text style={s.label}>{L.hearingDate}</Text>{txt(extraction?.case_details?.hearing_date, s.value)}</View>
          </View>
        </View>

        {/* ── Parties ── */}
        <View style={s.section} wrap={false}>
          <Text style={s.sectionTitle}>{L.parties}</Text>
          <View style={s.card}>
            <View style={s.row}><Text style={s.label}>{L.plaintiff}</Text>{txt(extraction?.parties?.plaintiff, s.value)}</View>
            <View style={extraction?.parties?.other_parties?.length ? s.row : s.rowLast}>
              <Text style={s.label}>{L.defendant}</Text>{txt(extraction?.parties?.defendant, s.value)}
            </View>
            {extraction?.parties?.other_parties?.map((p, i, arr) => (
              <View key={i} style={i === arr.length - 1 ? s.rowLast : [s.row, { marginTop: 2 }]}>
                <Text style={s.label}>{L.otherParty} {i + 1}</Text>
                {txt(p, s.value)}
              </View>
            ))}
          </View>
        </View>

        {/* ── Final Order ── */}
        {extraction?.final_order && (
          <View style={s.section}>
            <Text style={s.sectionTitle}>{L.finalOrder}</Text>
            <View style={s.card}>
              {txt(extraction.final_order, s.bodyText)}
            </View>
          </View>
        )}

        {/* ── Deadlines ── */}
        {extraction?.deadlines?.length ? (
          <View style={s.section}>
            <Text style={s.sectionTitle}>{L.deadlines}</Text>
            <View style={s.card}>
              {extraction.deadlines.map((d, i) => (
                <View key={i} style={[s.listRow, i === extraction.deadlines.length - 1 ? { marginBottom: 0 } : {}]}>
                  <Text style={s.bullet}>·</Text>
                  {txt(d, s.listText)}
                </View>
              ))}
            </View>
          </View>
        ) : null}

        {/* ── Citations ── */}
        {extraction?.citations?.length ? (
          <View style={s.section}>
            <Text style={s.sectionTitle}>{L.citations}</Text>
            <View style={s.card}>
              {extraction.citations.map((c, i, arr) => (
                <View key={i} style={[s.citRow, i === arr.length - 1 ? { borderBottomWidth: 0 } : {}]}>
                  <Text style={s.citPage}>{L.pageAbbrev}{c.page}</Text>
                  {txt(c.text, s.citText)}
                </View>
              ))}
            </View>
          </View>
        ) : null}

        {/* ── Action Plan ── */}
        {actionPlan && (
          <View style={s.section}>
            <Text style={s.sectionTitle}>{L.actionPlan}</Text>
            <View style={s.card}>
              {/* Decision + Department */}
              <View style={[s.row, { marginBottom: 10, alignItems: 'center' }]}>
                <Text style={s.label}>{L.decision}</Text>
                <View style={[s.badge, actionPlan.decision === 'comply' ? s.badgeComply : s.badgeAppeal]}>
                  <Text style={{ fontFamily: 'Helvetica-Bold', fontSize: 9 }}>{actionPlan.decision?.toUpperCase()}</Text>
                </View>
              </View>
              <View style={[s.row, { marginBottom: 14 }]}>
                <Text style={s.label}>{L.department}</Text>
                {txt(actionPlan.department, s.value)}
              </View>

              {/* Required Actions sub-heading */}
              {actionPlan.actions?.length ? (
                <>
                  <Text style={[s.sectionTitle, { marginBottom: 6, fontSize: 7 }]}>{L.requiredActions}</Text>
                  {actionPlan.actions.map((a, i, arr) => (
                    <View key={i} style={[s.actionRow, i === arr.length - 1 ? { borderBottomWidth: 0, paddingBottom: 0 } : {}]}>
                      <Text style={s.actionNum}>{String(i + 1).padStart(2, '0')}</Text>
                      <View style={s.actionBody}>
                        {txt(a.action, s.actionText)}
                        {a.deadline && (
                          <Text style={[s.actionDeadline, { fontFamily: ff }]}>{L.dueLabel}: {a.deadline}</Text>
                        )}
                      </View>
                    </View>
                  ))}
                </>
              ) : null}
            </View>
          </View>
        )}

        {/* ── Footer (repeats on every page) ── */}
        <View style={s.footer} fixed>
          <Text>{L.footerText}</Text>
          <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>

      </Page>
    </Document>
  );
}
